script: true
notifications:
  email: false
env:
  - FOO=1
  - FOO=2
conditions: v1
jobs:
  include:
    - stage: Yo!
      script: echo stages
      # on v0 this would produce a parse error, which currently returns `true`, and thus passes
      if: branch NOT IN (sf-stages-passing)
